export type B3CattleOptionSettlementInput = { optionPosition: "LONG" | "SHORT"; optionType: "CALL" | "PUT"; contracts: number; strikeBrlPerArroba: number; underlyingSettlementBrlPerArroba: number; underlyingSymbol: string; b3Lineage: { sourceId: "B3_PUBLIC_FILES"; sourceAsOf: string; sourceFile: string; sourceHashSha256: string } };
export type B3CattleOptionSettlementResult = { method: "B3_BGI_OPTION_INTRINSIC_SETTLEMENT_SCENARIO"; formulaVersion: "1.0.0"; contractSizeArrobas: 330; exerciseStyle: "AMERICAN"; intrinsicBrlPerArroba: number; grossExerciseBrl: number; exerciseEligibility: "in_the_money" | "out_of_the_money_or_at_the_money"; pricingStatus: "intrinsic_settlement_scenario_not_option_mtm"; blockedMetrics: Array<"premium_mtm" | "implied_volatility" | "greeks">; calculation: string; lineage: B3CattleOptionSettlementInput["b3Lineage"] & { underlyingSymbol: string; productSpecificationFile: string; productSpecificationHashSha256: string } };

/** Ficha B3 BGI: opção americana, 330 arrobas e exercício automático condicionado no vencimento. */
export function calculateB3CattleOptionIntrinsicSettlement(input: B3CattleOptionSettlementInput): B3CattleOptionSettlementResult {
  if (!Number.isInteger(input.contracts) || input.contracts <= 0) throw new Error("A quantidade de contratos deve ser inteira e positiva.");
  if (!Number.isFinite(input.strikeBrlPerArroba) || input.strikeBrlPerArroba <= 0 || !Number.isFinite(input.underlyingSettlementBrlPerArroba) || input.underlyingSettlementBrlPerArroba <= 0) throw new Error("Strike e preço de liquidação devem ser positivos e finitos.");
  if (!input.underlyingSymbol.trim() || !input.b3Lineage.sourceAsOf || !input.b3Lineage.sourceFile || !/^[a-f0-9]{64}$/.test(input.b3Lineage.sourceHashSha256)) throw new Error("O cenário exige símbolo, data-base, arquivo e hash SHA-256 do boletim B3.");
  const rawIntrinsic = input.optionType === "CALL" ? input.underlyingSettlementBrlPerArroba - input.strikeBrlPerArroba : input.strikeBrlPerArroba - input.underlyingSettlementBrlPerArroba;
  const intrinsicBrlPerArroba = Math.max(rawIntrinsic, 0);
  const direction = input.optionPosition === "LONG" ? 1 : -1;
  return { method: "B3_BGI_OPTION_INTRINSIC_SETTLEMENT_SCENARIO", formulaVersion: "1.0.0", contractSizeArrobas: 330, exerciseStyle: "AMERICAN", intrinsicBrlPerArroba, grossExerciseBrl: direction * input.contracts * 330 * intrinsicBrlPerArroba, exerciseEligibility: intrinsicBrlPerArroba > 0 ? "in_the_money" : "out_of_the_money_or_at_the_money", pricingStatus: "intrinsic_settlement_scenario_not_option_mtm", blockedMetrics: ["premium_mtm", "implied_volatility", "greeks"], calculation: "resultado = sinal × contratos × 330 arrobas × max(sinal_opção × (preço_liquidação_B3 − strike), 0)", lineage: { ...input.b3Lineage, underlyingSymbol: input.underlyingSymbol, productSpecificationFile: "bgi_opcao_especificacao.html", productSpecificationHashSha256: "76ca02fd7e891be44a82a1c335e3ba660629151383b42b53282b45b8bbf040f8" } };
}
