export type B3SoyOptionSettlementInput = { optionPosition: "LONG" | "SHORT"; optionType: "CALL" | "PUT"; contracts: number; strikeUsdPerTon: number; underlyingSettlementUsdPerTon: number; underlyingSymbol: string; b3Lineage: { sourceId: "B3_PUBLIC_FILES"; sourceAsOf: string; sourceFile: string; sourceHashSha256: string } };
export type B3SoyOptionSettlementResult = { method: "B3_SOY_OPTION_INTRINSIC_SETTLEMENT_SCENARIO"; formulaVersion: "1.0.0"; contractSizeMetricTons: 34; exerciseStyle: "AMERICAN"; intrinsicUsdPerTon: number; grossExerciseUsd: number; exerciseEligibility: "in_the_money" | "out_of_the_money_or_at_the_money"; pricingStatus: "intrinsic_settlement_scenario_not_option_mtm"; blockedMetrics: Array<"premium_mtm" | "implied_volatility" | "greeks">; calculation: string; lineage: B3SoyOptionSettlementInput["b3Lineage"] & { underlyingSymbol: string; productSpecificationFile: string; productSpecificationHashSha256: string } };

/** Ficha B3 SOY: opção americana, 34 t e cotação em US$/t. */
export function calculateB3SoyOptionIntrinsicSettlement(input: B3SoyOptionSettlementInput): B3SoyOptionSettlementResult {
  if (!Number.isInteger(input.contracts) || input.contracts <= 0) throw new Error("A quantidade de contratos deve ser inteira e positiva.");
  if (!Number.isFinite(input.strikeUsdPerTon) || input.strikeUsdPerTon <= 0 || !Number.isFinite(input.underlyingSettlementUsdPerTon) || input.underlyingSettlementUsdPerTon <= 0) throw new Error("Strike e preço de liquidação devem ser positivos e finitos.");
  if (!input.underlyingSymbol.trim() || !input.b3Lineage.sourceAsOf || !input.b3Lineage.sourceFile || !/^[a-f0-9]{64}$/.test(input.b3Lineage.sourceHashSha256)) throw new Error("O cenário exige símbolo, data-base, arquivo e hash SHA-256 do boletim B3.");
  const intrinsicUsdPerTon = Math.max(input.optionType === "CALL" ? input.underlyingSettlementUsdPerTon - input.strikeUsdPerTon : input.strikeUsdPerTon - input.underlyingSettlementUsdPerTon, 0);
  return { method: "B3_SOY_OPTION_INTRINSIC_SETTLEMENT_SCENARIO", formulaVersion: "1.0.0", contractSizeMetricTons: 34, exerciseStyle: "AMERICAN", intrinsicUsdPerTon, grossExerciseUsd: (input.optionPosition === "LONG" ? 1 : -1) * input.contracts * 34 * intrinsicUsdPerTon, exerciseEligibility: intrinsicUsdPerTon > 0 ? "in_the_money" : "out_of_the_money_or_at_the_money", pricingStatus: "intrinsic_settlement_scenario_not_option_mtm", blockedMetrics: ["premium_mtm", "implied_volatility", "greeks"], calculation: "resultado = sinal × contratos × 34 toneladas × max(sinal_opção × (preço_liquidação_B3 − strike), 0)", lineage: { ...input.b3Lineage, underlyingSymbol: input.underlyingSymbol, productSpecificationFile: "soy_opcao_especificacao.html", productSpecificationHashSha256: "f9d50c2e0cb249a8c5310010c0fbc0033b5c39598b14a281c2ba29d10920908a" } };
}
