import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ChartNoAxesCombined } from "lucide-react";
import React, { useMemo } from "react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { DiFutureCurveDataset } from "../../../server/domain/diFutureCurve";

/** Evidência visual de vértices DI1 observados; não interpola nem projeta taxas. */
export default function B3DiCurveEvidenceChart({ curve }: { curve: DiFutureCurveDataset | null }) {
  const points = useMemo(() => (curve?.dataframe ?? []).map(point => ({ symbol: point.symbol, maturity: point.maturity, businessDays: point.business_days_to_maturity, rate: point.adjusted_rate_pct_aa252 })).filter(point => typeof point.rate === "number" && Number.isFinite(point.rate)).sort((left, right) => (left.businessDays ?? Number.MAX_SAFE_INTEGER) - (right.businessDays ?? Number.MAX_SAFE_INTEGER)), [curve]);
  if (!curve || points.length === 0) return null;
  return <Card className="mt-5 border-[#c9e3dc] bg-[#fbfefd] shadow-none"><CardHeader className="border-b border-[#e7f1ed] pb-4"><div className="flex items-start gap-3"><ChartNoAxesCombined className="mt-0.5 h-5 w-5 text-[#218471]" /><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#3a806f]">Evidência B3 · curva observada</p><CardTitle className="mt-1 text-base text-[#17363e]">Vértices DI1 publicados — {curve.asof}</CardTitle><p className="mt-1 text-xs leading-5 text-[#607a76]">Cada ponto é um vencimento recuperado da B3. A linha apenas conecta os vértices observados para leitura visual; não há interpolação, taxa forward, projeção ou preço substituto.</p></div></div></CardHeader><CardContent className="p-4 sm:p-5"><div className="h-[250px]"><ResponsiveContainer width="100%" height="100%"><LineChart data={points} margin={{ top: 14, right: 18, bottom: 0, left: -18 }}><XAxis dataKey="businessDays" tickLine={false} axisLine={false} tick={{ fill: "#66837d", fontSize: 10 }} tickFormatter={value => `${value} du`} minTickGap={30} /><YAxis tickLine={false} axisLine={false} tick={{ fill: "#66837d", fontSize: 10 }} tickFormatter={value => `${new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 2 }).format(Number(value))}%`} width={48} /><Tooltip labelFormatter={(_, payload) => { const point = payload?.[0]?.payload as { symbol?: string; maturity?: string; businessDays?: number } | undefined; return point ? `${point.symbol ?? "DI1"} · venc. ${point.maturity ?? "não informado"} · ${point.businessDays ?? "—"} du` : "Vértice DI1"; }} formatter={value => `${new Intl.NumberFormat("pt-BR", { minimumFractionDigits: 4, maximumFractionDigits: 4 }).format(Number(value))}% a.a. / 252`} contentStyle={{ border: "1px solid #cfe3dd", borderRadius: 12, fontSize: 12 }} /><Line type="monotone" dataKey="rate" name="Taxa de ajuste" stroke="#1e8a74" strokeWidth={2.5} dot={{ r: 3, fill: "#1e8a74", strokeWidth: 0 }} activeDot={{ r: 5 }} /></LineChart></ResponsiveContainer></div><p className="mt-2 text-[10px] leading-4 text-[#6b847e]">Fonte: B3 · {points.length} vértice(s) · arquivo e hash preservados na tabela de evidências acima.</p></CardContent></Card>;
}
