import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Scale } from "lucide-react";
import React from "react";
import type { CanonicalHedgeDataframes } from "../../../server/domain/dataframes";

function statusText(status: "eligible_with_market_data" | "contract_required" | "blocked", hasObservation: boolean, hasSizing: boolean, hasResult: boolean) {
  if (status === "blocked") return "Bloqueada";
  if (hasResult) return "Resultado vinculado";
  if (hasSizing) return "Cobertura publicada";
  if (hasObservation) return "Série B3 vinculada";
  return status === "contract_required" ? "Exige contrato bilateral" : "Aguardando série e contrato";
}

/** Compara alternativas do catálogo por sua evidência e bloqueio, não por recomendação ou rentabilidade presumida. */
type LineageRow = { source_id: string; source_file: string; source_asof: string | null; source_hash_sha256: string | null };
export default function EligibleAlternativesComparisonCard({ dataframes, lineage = [], selectedAlternativeId, onSelectAlternative }: { dataframes: CanonicalHedgeDataframes; lineage?: LineageRow[]; selectedAlternativeId?: string | null; onSelectAlternative?: (alternativeId: string) => void }) {
  const situation = dataframes.economic_situation_dataframe[0];
  const risk = dataframes.risk_factor_dataframe[0];
  if (!situation || !risk) return <Card className="mt-7 rounded-2xl border-[#d7e7e2] bg-white shadow-none"><CardHeader className="border-b border-[#edf2f0] pb-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#6c8990]">Alternativas de hedge</p><CardTitle className="mt-1 text-base text-[#17363e]">Comparação condicionada à situação econômica</CardTitle></div><Scale className="h-5 w-5 text-[#328a7a]" /></div></CardHeader><CardContent className="px-5 py-7 text-center text-sm text-[#71878e]">Faça um diagnóstico de exposição para materializar alternativas e seus bloqueios quantitativos.</CardContent></Card>;
  return <Card className="mt-7 rounded-2xl border-[#d7e7e2] bg-white shadow-none"><CardHeader className="border-b border-[#edf2f0] pb-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#6c8990]">Etapa 2 · alternativas declaradas</p><CardTitle className="mt-1 text-base text-[#17363e]">Como este risco pode ser protegido?</CardTitle></div><Scale className="h-5 w-5 text-[#328a7a]" /></div><p className="mt-2 text-xs leading-5 text-[#607a76]">A exposição <strong>{situation.description}</strong> está ligada ao fator <strong>{risk.risk_factor}</strong>. Escolha uma alternativa para ver as evidências permitidas e os próximos passos. O app não recomenda nem seleciona uma operação por você.</p></CardHeader><CardContent className="grid gap-3 p-5 md:grid-cols-2 xl:grid-cols-3">{dataframes.hedge_alternative_dataframe.map(alternative => {
    const sizing = dataframes.hedge_sizing_dataframe.find(row => row.alternative_id === alternative.alternative_id);
    const result = dataframes.scenario_result_dataframe.find(row => row.alternative_id === alternative.alternative_id);
    const coverage = sizing?.coverage_target_pct === null || sizing?.coverage_target_pct === undefined ? "Não dimensionada" : `${new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 4 }).format(sizing.coverage_target_pct)}%`;
    const selectedB3 = dataframes.b3_observation_link_dataframe?.find(item => item.alternative_id === alternative.alternative_id);
    const observedB3 = alternative.source_ids.includes("B3_PUBLIC_FILES") ? lineage.find(item => item.source_id === "B3_PUBLIC_FILES") : undefined;
    const active = selectedAlternativeId === alternative.alternative_id;
    return <article key={alternative.alternative_id} className={`rounded-xl border p-4 transition ${active ? "border-[#4ca990] bg-[#effbf7] shadow-[0_12px_28px_-24px_rgba(20,94,82,.7)]" : "border-[#dce9e5] bg-[#fbfdfc]"}`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[#17363e]">{alternative.label}</p><p className="mt-1 text-[11px] text-[#54726c]">{alternative.hedge_direction === "BUY" ? "Proteção por posição comprada" : "Proteção por posição vendida"}</p></div><Badge variant="outline" className={active ? "border-[#8bd0bf] bg-white text-[10px] text-[#166657]" : "border-[#d7e7e2] bg-white text-[10px] text-[#466761]"}>{statusText(alternative.eligibility_status, Boolean(selectedB3), Boolean(sizing && sizing.sizing_status === "sized"), Boolean(result && result.result_status === "SUCCESS"))}</Badge></div><div className="mt-4 space-y-3 text-xs leading-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#6f8984]">Para utilizar</p><p className="mt-1 text-[#54726c]">{alternative.required_data.join(" · ")}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#6f8984]">Evidência atual</p><p className="mt-1 text-[#54726c]">{selectedB3 ? `${selectedB3.family} · ${selectedB3.symbol} · venc. ${selectedB3.maturity ?? "não informado"}` : observedB3 ? "Arquivo oficial B3 está na sessão; a série ainda não foi escolhida." : alternative.eligibility_status === "contract_required" ? "Exige contrato bilateral declarado e hasheado." : "Aguardando série, contrato ou dado oficial compatível."}</p></div><div><p className="text-[10px] font-semibold uppercase tracking-[.1em] text-[#6f8984]">Cobertura e cenário</p><p className="mt-1 text-[#54726c]">{coverage}{result?.economic_result === null || result?.economic_result === undefined ? " · cenário ainda não calculado" : ` · resultado ${result.economic_result} ${result.result_currency ?? ""}`}</p>{result?.limitation && <p className="mt-1 text-[10px] leading-4 text-[#71858a]">{result.limitation}</p>}</div></div><button type="button" onClick={() => onSelectAlternative?.(alternative.alternative_id)} className={`mt-4 w-full rounded-lg px-3 py-2 text-xs font-semibold transition ${active ? "bg-[#1b6258] text-white hover:bg-[#164e46]" : "border border-[#bcd9d1] bg-white text-[#1b6157] hover:bg-[#edf9f5]"}`}>{active ? "Alternativa em análise" : "Analisar esta alternativa"}</button><p className="mt-3 text-[10px] leading-4 text-[#8d6740]">{sizing?.blocking_reason ?? alternative.blocking_reason ?? "Antes do dimensionamento, valide os parâmetros e as evidências exigidas."}</p></article>;
  })}</CardContent></Card>;
}
