import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Scale } from "lucide-react";
import React from "react";
import type { CanonicalHedgeDataframes } from "../../../server/domain/dataframes";

function statusText(status: "eligible_with_market_data" | "contract_required" | "blocked", hasObservation: boolean, hasSizing: boolean, hasResult: boolean) {
  if (status === "blocked") return "Bloqueada";
  if (hasResult) return "Resultado vinculado";
  if (hasSizing) return "Cobertura publicada";
  if (hasObservation) return "Série B3 vinculada";
  return status === "contract_required" ? "Exige contrato bilateral" : "Aguardando série e contrato";
}

/** Compara alternativas do catálogo por sua evidência e bloqueio, não por recomendação ou rentabilidade presumida. */
type LineageRow = { source_id: string; source_file: string; source_asof: string | null; source_hash_sha256: string | null };
export default function EligibleAlternativesComparisonCard({ dataframes, lineage = [] }: { dataframes: CanonicalHedgeDataframes; lineage?: LineageRow[] }) {
  const situation = dataframes.economic_situation_dataframe[0];
  const risk = dataframes.risk_factor_dataframe[0];
  if (!situation || !risk) return <Card className="mt-7 rounded-2xl border-[#d7e7e2] bg-white shadow-none"><CardHeader className="border-b border-[#edf2f0] pb-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#6c8990]">Alternativas de hedge</p><CardTitle className="mt-1 text-base text-[#17363e]">Comparação condicionada à situação econômica</CardTitle></div><Scale className="h-5 w-5 text-[#328a7a]" /></div></CardHeader><CardContent className="px-5 py-7 text-center text-sm text-[#71878e]">Faça um diagnóstico de exposição para materializar alternativas e seus bloqueios quantitativos.</CardContent></Card>;
  return <Card className="mt-7 rounded-2xl border-[#d7e7e2] bg-white shadow-none"><CardHeader className="border-b border-[#edf2f0] pb-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#6c8990]">Alternativas de hedge</p><CardTitle className="mt-1 text-base text-[#17363e]">Comparação auditável — {situation.description}</CardTitle></div><Scale className="h-5 w-5 text-[#328a7a]" /></div><p className="mt-2 text-xs leading-5 text-[#607a76]">Fator de risco: <strong>{risk.risk_factor}</strong>. A comparação não recomenda uma operação: só apresenta alternativas, premissas e bloqueios. Resultado econômico, preço e cobertura só aparecem quando a série, contrato, vencimento e parâmetros forem validados.</p></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="min-w-[1120px] w-full text-left text-xs"><thead className="bg-[#f6fbf9] text-[10px] uppercase tracking-[.1em] text-[#69847f]"><tr><th className="px-5 py-3 font-semibold">Alternativa / direção</th><th className="px-5 py-3 font-semibold">Dados observados e fonte</th><th className="px-5 py-3 font-semibold">Premissas exigidas</th><th className="px-5 py-3 font-semibold">Relação de cobertura</th><th className="px-5 py-3 font-semibold">Resultado de cenário</th><th className="px-5 py-3 font-semibold">Bloqueio quantitativo</th></tr></thead><tbody className="divide-y divide-[#edf2f0]">{dataframes.hedge_alternative_dataframe.map(alternative => {
    const sizing = dataframes.hedge_sizing_dataframe.find(row => row.alternative_id === alternative.alternative_id);
    const result = dataframes.scenario_result_dataframe.find(row => row.alternative_id === alternative.alternative_id);
    const coverage = sizing?.coverage_target_pct === null || sizing?.coverage_target_pct === undefined ? "Não dimensionada" : `${new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 4 }).format(sizing.coverage_target_pct)}%`;
    const selectedB3 = dataframes.b3_observation_link_dataframe?.find(item => item.alternative_id === alternative.alternative_id);
    const observedB3 = alternative.source_ids.includes("B3_PUBLIC_FILES") ? lineage.find(item => item.source_id === "B3_PUBLIC_FILES") : undefined;
    return <tr key={alternative.alternative_id} className="align-top"><td className="px-5 py-4"><p className="font-medium text-[#17363e]">{alternative.label}</p><p className="mt-1 text-[10px] text-[#617c76]">{alternative.hedge_direction === "BUY" ? "Posição de proteção: compra" : "Posição de proteção: venda"}</p><Badge variant="outline" className="mt-2 border-[#d7e7e2] bg-[#fbfdfc] text-[10px] text-[#466761]">{statusText(alternative.eligibility_status, Boolean(selectedB3), Boolean(sizing && sizing.sizing_status === "sized"), Boolean(result && result.result_status === "SUCCESS"))}</Badge></td><td className="max-w-[190px] px-5 py-4 leading-5 text-[#5c7771]">{selectedB3 ? <><p><strong>{selectedB3.family} · {selectedB3.symbol}</strong> · {selectedB3.instrument_type} · venc. {selectedB3.maturity ?? "não informado"}</p><p className="mt-1 break-all font-mono text-[10px]">Preço: {selectedB3.price_source.source_file} · {selectedB3.price_source.source_asof} · {selectedB3.price_source.source_hash_sha256}</p><p className="mt-1 break-all font-mono text-[10px]">Cadastro: {selectedB3.instrument_source.source_file} · {selectedB3.instrument_source.source_asof} · {selectedB3.instrument_source.source_hash_sha256}</p></> : observedB3 ? <><p>Arquivo B3 carregado na sessão; ainda sem seleção automática de símbolo ou vencimento.</p><p className="mt-1 break-all font-mono text-[10px]">{observedB3.source_file} · {observedB3.source_asof ?? "sem data-base"} · {observedB3.source_hash_sha256 ?? "sem hash"}</p></> : <><p>Nenhuma série ou contrato foi associado automaticamente à alternativa.</p><p className="mt-1 font-mono text-[10px]">Fontes requeridas: {alternative.source_ids.join(" · ")}</p></>}</td><td className="max-w-[220px] px-5 py-4 leading-5 text-[#5c7771]">{alternative.required_data.join(" · ")}</td><td className="px-5 py-4"><p className="font-semibold text-[#315d59]">{coverage}</p><p className="mt-1 text-[10px] leading-4 text-[#71878e]">{sizing?.hedge_quantity === null || sizing?.hedge_quantity === undefined ? "Quantidade não calculada" : `${sizing.hedge_quantity} ${sizing.hedge_unit ?? ""}`}</p></td><td className="max-w-[180px] px-5 py-4"><p className="font-mono text-[10px] text-[#456761]">{result?.economic_result === null || result?.economic_result === undefined ? "Não calculado" : `${result.economic_result} ${result.result_currency ?? ""}`}</p><p className="mt-1 text-[10px] leading-4 text-[#71878e]">{result?.limitation ?? "Nenhum cenário vinculado à alternativa."}</p></td><td className="max-w-[230px] px-5 py-4 leading-5 text-[#8d6740]">{sizing?.blocking_reason ?? alternative.blocking_reason ?? "Preço, vencimento, contrato/unidade e parâmetros ainda precisam ser validados antes do dimensionamento."}</td></tr>;
  })}</tbody></table></div></CardContent></Card>;
}
