import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BadgeCheck, CircleAlert, GitFork, ShieldAlert } from "lucide-react";
import React from "react";
import type { CanonicalHedgeDataframes } from "../../../server/domain/dataframes";

type Snapshot = { scenario: { scenario_id: string; scenario_name: string; fx_shock_pct: null; rate_shock_bps: null; volatility_shock_pct: null; created_at_utc: string }; calculations: Array<{ calculation_id: string; scenario_id: string; method: string; formula_version: string; calculation_status: "SUCCESS"; result: Record<string, unknown>; warnings: string[]; calculated_at_utc: string }> };

export default function FraDi1StructureReferenceCard({ dataframes, onSnapshot }: { dataframes: CanonicalHedgeDataframes; onSnapshot?: (snapshot: Snapshot) => void }) {
  const alternative = dataframes.hedge_alternative_dataframe.find(row => row.alternative_kind === "B3_FRA_DI1");
  const legs = alternative ? (dataframes.b3_observation_link_dataframe ?? []).filter(row => row.alternative_id === alternative.alternative_id && row.family === "DI1" && row.instrument_type === "FUTURE" && row.maturity).sort((a, b) => (a.maturity ?? "").localeCompare(b.maturity ?? "")) : [];
  const nearLeg = legs[0];
  const farLeg = legs[1];
  const sameAsOf = Boolean(nearLeg && farLeg && nearLeg.price_source.source_asof === farLeg.price_source.source_asof && nearLeg.instrument_source.source_asof === farLeg.instrument_source.source_asof);
  const ready = Boolean(alternative && nearLeg && farLeg && nearLeg.instrument_id !== farLeg.instrument_id && sameAsOf);
  const register = () => {
    if (!ready || !alternative || !nearLeg || !farLeg) return;
    const createdAtUtc = new Date().toISOString();
    const scenarioId = `fra-di1-reference::${alternative.alternative_id}::${nearLeg.instrument_id}::${farLeg.instrument_id}`;
    onSnapshot?.({ scenario: { scenario_id: scenarioId, scenario_name: "Referência de estrutura FRA DI1", fx_shock_pct: null, rate_shock_bps: null, volatility_shock_pct: null, created_at_utc: createdAtUtc }, calculations: [{ calculation_id: `${scenarioId}::calculation`, scenario_id: scenarioId, method: "B3_FRA_DI1_LEG_REFERENCE", formula_version: "1.0.0", calculation_status: "SUCCESS", result: { near_di1_symbol: nearLeg.symbol, near_di1_maturity: nearLeg.maturity, far_di1_symbol: farLeg.symbol, far_di1_maturity: farLeg.maturity, source_asof: nearLeg.price_source.source_asof, near_source_hash_sha256: nearLeg.price_source.source_hash_sha256, far_source_hash_sha256: farLeg.price_source.source_hash_sha256, opposing_natures_required: true }, warnings: ["A B3 descreve o FRA DI1 como dois vencimentos DI1 em naturezas opostas e quantidades calibradas para neutralizar PU. Esta referência não calcula razão de contratos, PU neutro, taxa, DV01, MTM, margem ou resultado financeiro."], calculated_at_utc: createdAtUtc }] });
  };
  return <Card className="mt-7 rounded-2xl border-[#d7d5ee] bg-[#faf9ff] shadow-none"><CardHeader className="flex flex-row items-start justify-between border-b border-[#e8e6f4] pb-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-[#716d9c]">Operação estruturada</p><CardTitle className="mt-1 text-base text-[#37325f]">FRA DI1 — referência dos dois vencimentos</CardTitle></div><GitFork className="h-5 w-5 text-[#6154a2]" /></CardHeader><CardContent className="p-5"><p className="text-xs leading-5 text-[#625e79]">A B3 descreve o FRA DI1 (PU Neutro) como dois futuros DI1 em naturezas opostas. A plataforma registra somente os dois vértices observados e sua linhagem comum; não infere a calibração exigida pela estrutura.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-[#e3e0f0] bg-white p-3 text-xs text-[#504a67]"><p className="font-semibold text-[#39325c]">Vencimento próximo</p><p className="mt-1">{nearLeg ? `${nearLeg.symbol} · ${nearLeg.maturity}` : "Selecione o primeiro futuro DI1 no seletor B3."}</p></div><div className="rounded-xl border border-[#e3e0f0] bg-white p-3 text-xs text-[#504a67]"><p className="font-semibold text-[#39325c]">Vencimento distante</p><p className="mt-1">{farLeg ? `${farLeg.symbol} · ${farLeg.maturity}` : "Selecione um segundo futuro DI1 distinto no seletor B3."}</p></div></div>{ready ? <div className="mt-4 rounded-xl border border-[#cbe6dc] bg-[#f2fbf7] p-4"><div className="flex gap-2"><BadgeCheck className="h-5 w-5 shrink-0 text-[#228b6f]" /><div className="text-xs leading-5 text-[#3e665d]"><p className="font-semibold text-[#245d50]">Estrutura de evidência verificada</p><p>Os dois vencimentos DI1 são distintos e estão na mesma data-base B3. Lados opostos e quantidades calibradas continuam como requisitos para qualquer operação.</p></div></div>{onSnapshot && <Button className="mt-3" type="button" variant="outline" size="sm" onClick={register}>Registrar referência no histórico</Button>}</div> : <div className="mt-4 flex gap-2 rounded-xl border border-[#f0d7bf] bg-[#fff8ef] p-4 text-xs leading-5 text-[#8d5c2d]"><CircleAlert className="h-5 w-5 shrink-0" /><p>{!alternative ? "Diagnostique uma dívida CDI para expor a alternativa FRA DI1." : legs.length < 2 ? "Vincule dois futuros DI1 distintos à alternativa FRA no seletor de observações." : "Os dois futuros precisam compartilhar a mesma data-base B3."}</p></div>}<div className="mt-4 flex gap-2 text-xs leading-5 text-[#756f82]"><ShieldAlert className="mt-0.5 h-4 w-4 shrink-0 text-[#91723a]" /><p>Razão de contratos, PU neutro, taxa, DV01, MTM, margem, custo financeiro e resultado permanecem bloqueados. A estrutura não representa novo contrato nem mantém posições próprias ao fim do dia.</p></div></CardContent></Card>;
}
