import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Calculator, Loader2 } from "lucide-react";
import React, { useEffect, useMemo, useState } from "react";

type Snapshot = { scenario: { scenario_id: string; scenario_name: string; fx_shock_pct: number | null; rate_shock_bps: number | null; volatility_shock_pct: number | null; created_at_utc: string }; calculations: Array<{ calculation_id: string; scenario_id: string; method: string; formula_version: string; calculation_status: "SUCCESS" | "BLOCKED" | "WARNING"; result: Record<string, unknown>; warnings: string[]; calculated_at_utc: string }> };
const valid = (value: string) => /^2026-\d{2}-\d{2}$/.test(value);

export default function SelicOverAccumulationCard({ onSnapshot }: { onSnapshot?: (snapshot: Snapshot | null) => void }) {
  const [startDate, setStartDate] = useState("2026-08-03");
  const [endDate, setEndDate] = useState("2026-08-04");
  const input = valid(startDate) && valid(endDate) && startDate <= endDate ? { startDate, endDate } : null;
  const query = trpc.marketData.selicOverAccumulated.useQuery(input ?? { startDate: "2026-01-02", endDate: "2026-01-02" }, { enabled: false, retry: false });
  const scenarioId = useMemo(() => input ? `sgs11-over-${input.startDate}-${input.endDate}` : null, [input]);
  useEffect(() => { if (!query.data || !scenarioId) { onSnapshot?.(null); return; } const now = new Date().toISOString(); onSnapshot?.({ scenario: { scenario_id: scenarioId, scenario_name: `Fator over SGS 11 — ${query.data.startDate} a ${query.data.endDate}`, fx_shock_pct: null, rate_shock_bps: null, volatility_shock_pct: null, created_at_utc: now }, calculations: [{ calculation_id: `${scenarioId}-calculation`, scenario_id: scenarioId, method: query.data.method, formula_version: "1.0.0", calculation_status: "SUCCESS", result: { start_date: query.data.startDate, end_date: query.data.endDate, calendar_id: query.data.calendarId, observation_count: query.data.observationCount, accumulated_factor: query.data.accumulatedFactor, accumulated_pct: query.data.accumulatedPct, observations: query.data.observations, lineage: query.data.lineage }, warnings: query.data.limitations, calculated_at_utc: now }] }); }, [onSnapshot, query.data, scenarioId]);
  return <Card className="mt-7 rounded-2xl border-[#dce8e5] bg-white shadow-none"><CardHeader className="border-b border-[#edf2f0] pb-4"><CardTitle className="text-base text-[#17363e]">Fator acumulado da taxa over — SGS 11</CardTitle><p className="mt-2 text-xs leading-5 text-[#607a76]">Capitaliza exclusivamente observações diárias BCB SGS 11, conferidas contra o calendário bancário ANBIMA 2026. Não anualiza, não constrói curva e não completa dias ausentes.</p></CardHeader><CardContent className="p-5"><div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><div><Label htmlFor="over-start">Data inicial</Label><Input id="over-start" type="date" value={startDate} onChange={event => setStartDate(event.target.value)} className="mt-1.5" /></div><div><Label htmlFor="over-end">Data final</Label><Input id="over-end" type="date" value={endDate} onChange={event => setEndDate(event.target.value)} className="mt-1.5" /></div><Button onClick={() => query.refetch()} disabled={!input || query.isFetching} className="bg-[#173c45] text-white">{query.isFetching ? <Loader2 className="animate-spin" /> : <Calculator />} Calcular</Button></div>{query.isError && <p className="mt-4 rounded-lg bg-[#fff8ed] p-3 text-xs text-[#8d6740]">A série over não pôde ser acumulada para o intervalo: a sequência diária oficial ou o calendário válido não estão completos. Nenhuma taxa foi anualizada ou substituída.</p>}{query.data && <div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-[#f4faf8] p-3"><p className="text-[10px] uppercase tracking-[.1em]">Fator</p><p className="mt-1 font-mono font-semibold">{query.data.accumulatedFactor.toFixed(8)}</p></div><div className="rounded-lg bg-[#f4faf8] p-3"><p className="text-[10px] uppercase tracking-[.1em]">Acumulado</p><p className="mt-1 font-mono font-semibold">{query.data.accumulatedPct.toFixed(6)}%</p></div><div className="rounded-lg bg-[#f4faf8] p-3"><p className="text-[10px] uppercase tracking-[.1em]">Observações</p><p className="mt-1 font-mono font-semibold">{query.data.observationCount}</p></div></div>}<div className="mt-4 flex gap-2 text-[11px] leading-5 text-[#8d6740]"><AlertTriangle className="h-4 w-4 shrink-0" /><p>Resultado restrito ao fator over observado. MTM, curva, taxa contratual, taxa anual e precificação permanecem bloqueados.</p></div></CardContent></Card>;
}
